services:
  db:
    image: postgres:15-alpine
    container_name: sguard-db
    restart: always
    environment:
      POSTGRES_USER: sguard_user
      POSTGRES_PASSWORD: sguard_password
      POSTGRES_DB: sguard_db
    ports:
      - "5433:5432"
    volumes:
      - sguard_postgres_data:/var/lib/postgresql/data



  tomcat:
    image: tomcat:10-jdk17
    container_name: sguard-tomcat
    restart: always
    ports:
      - "8081:8080"
    volumes:
      - ./backend/tomcat_webapps:/usr/local/tomcat/webapps
    environment:
      - JAVA_OPTS=-Dfile.encoding=UTF-8


  backend:
    build: ./backend
    container_name: sguard-backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://sguard_user:sguard_password@db:5432/sguard_db
      SMTP_HOST: ${SMTP_HOST:-smtp.gmail.com}
      SMTP_PORT: ${SMTP_PORT:-587}
      SMTP_USER: ${SMTP_USER:-your-email@gmail.com}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-your-app-password}
      DIFY_API_KEY: app-TSlqmp329iKOzpXUP90iC6Kw
      DIFY_API_BASE: ${DIFY_API_BASE:-https://api.dify.ai/v1}
      DIFY_DATASET_ID: ${DIFY_DATASET_ID:-XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX}
    depends_on:
      - db
    volumes:
      - ./backend:/app

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: sguard-tunnel
    command: tunnel --url http://backend:8000
    depends_on:
      - backend
    restart: always

  frontend:
    build: ./frontend
    container_name: sguard-frontend
    ports:
      - "5174:5173"
    environment:
      VITE_API_URL: http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  pgadmin:
    image: dpage/pgadmin4
    container_name: sguard-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@sguard.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"
    depends_on:
      - db

volumes:
  sguard_postgres_data:
