-- Restore full organization hierarchy (18 subsidiaries + 65 detailed Shinhan DS units)
DELETE FROM organizations;

-- 1. Insert 18 subsidiaries (Depth 1)
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (1, '신한DS', 'COM_001', NULL, 1, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (2, '신한금융지주', 'COM_002', NULL, 1, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (3, '신한은행', 'COM_003', NULL, 1, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (4, '신한카드', 'COM_004', NULL, 1, 4);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (5, '신한투자증권', 'COM_005', NULL, 1, 5);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (6, '신한라이프', 'COM_006', NULL, 1, 6);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (7, '신한캐피탈', 'COM_007', NULL, 1, 7);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (8, '신한자산운용', 'COM_008', NULL, 1, 8);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (9, '신한저축은행', 'COM_009', NULL, 1, 9);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (10, '신한AI', 'COM_010', NULL, 1, 10);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (11, '제주은행', 'COM_011', NULL, 1, 11);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (12, '신한벤처투자', 'COM_012', NULL, 1, 12);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (13, '신한리츠운용', 'COM_013', NULL, 1, 13);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (14, '신한대체투자운용', 'COM_014', NULL, 1, 14);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (15, '신한자산신탁', 'COM_015', NULL, 1, 15);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (16, '신한펀드파트너스', 'COM_016', NULL, 1, 16);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (17, '신한금융플러스', 'COM_017', NULL, 1, 17);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (18, '신한큐브리스크컨설팅', 'COM_018', NULL, 1, 18);

-- 2. Insert detail units for Shinhan DS (nested under ID 1)
-- ID 101 to 165, Depth 2-5
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (101, '임원실', 'DIV-001', 1, 2, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (102, '감사팀', 'DEP-001', 101, 3, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (103, '준법지원팀', 'DEP-002', 101, 3, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (104, '경영부문', 'DIV-002', 1, 2, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (105, '경영기획본부', 'DEP-003', 104, 3, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (106, '경영기획팀', 'TEA-001', 105, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (107, '재무팀', 'TEA-002', 105, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (108, '인사팀', 'TEA-003', 105, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (109, '현지법인', 'TEA-004', 105, 4, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (110, '경영지원본부', 'DEP-004', 104, 3, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (111, '품질혁신팀', 'TEA-005', 110, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (112, '구매계약팀', 'TEA-006', 110, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (113, '업무지원팀', 'TEA-007', 110, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (114, '변화추진SAQ', 'TEA-008', 110, 4, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (115, '미래성장부문', 'DIV-003', 1, 2, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (116, 'AX본부', 'DEP-005', 115, 3, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (117, 'AI&DATA팀', 'TEA-009', 116, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (118, 'AI운영팀', 'TEA-010', 116, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (119, '클라우드 본부', 'DEP-006', 115, 3, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (120, '클라우드사업팀', 'TEA-011', 119, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (121, '클라우드운영팀', 'TEA-012', 119, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (122, '그룹클라우드팀', 'TEA-013', 119, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (123, '개발운영부문', 'DIV-004', 1, 2, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (124, '그룹공통본부', 'DEP-007', 123, 3, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (125, '공통지원팀', 'TEA-014', 124, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (126, '공통플랫폼팀', 'TEA-015', 124, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (127, '뱅킹본부', 'DEP-008', 123, 3, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (128, '뱅킹코어팀', 'TEA-016', 127, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (129, '뱅킹정보팀', 'TEA-017', 127, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (130, '뱅킹글로벌팀', 'TEA-018', 127, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (131, '금융본부', 'DEP-009', 123, 3, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (132, '카드개발팀', 'TEA-019', 131, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (133, '상담', 'PRT-001', 132, 5, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (134, '홈페이지', 'PRT-002', 132, 5, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (135, '오토금융', 'PRT-003', 132, 5, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (136, '모바일지원', 'PRT-004', 132, 5, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (137, '내부관리지원', 'PRT-005', 132, 5, 4);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (138, '재무정보', 'PRT-006', 132, 5, 5);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (139, 'BD플렛폼지원', 'PRT-007', 132, 5, 6);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (140, '마케팅', 'PRT-008', 132, 5, 7);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (141, '포인트', 'PRT-009', 132, 5, 8);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (142, '데이터비즈', 'PRT-010', 132, 5, 9);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (143, '통합메시지', 'PRT-011', 132, 5, 10);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (144, '증권개발팀', 'TEA-020', 131, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (145, '증권채널팀', 'TEA-021', 131, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (146, '라이프개발팀', 'TEA-022', 131, 4, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (147, 'DX본부', 'DEP-010', 123, 3, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (148, 'DX추진팀', 'TEA-023', 147, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (149, '금융DX팀', 'TEA-024', 147, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (150, '모바일DX팀', 'TEA-025', 147, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (151, '글로벌DX팀', 'TEA-026', 147, 4, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (152, '인프라&보안부문', 'DIV-005', 1, 2, 4);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (153, '인프라 본부', 'DEP-011', 152, 3, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (154, '인프라 SRE팀', 'TEA-027', 153, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (155, '뱅킹IS팀', 'TEA-028', 153, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (156, '뱅킹정보IS팀', 'TEA-029', 153, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (157, '뱅킹통신보안팀', 'TEA-030', 153, 4, 3);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (158, '카드IS팀', 'TEA-031', 153, 4, 4);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (159, '증권IS팀', 'TEA-032', 153, 4, 5);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (160, '라이프 IS팀', 'TEA-033', 153, 4, 6);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (161, '정보보호본부', 'DEP-012', 152, 3, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (162, '보안컨설팅팀', 'TEA-034', 161, 4, 0);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (163, '보안사업팀', 'TEA-035', 161, 4, 1);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (164, '사이버대응팀', 'TEA-036', 161, 4, 2);
INSERT INTO organizations (id, name, code, parent_id, depth, sort_order) VALUES (165, 'TFT외부직원', 'DIV-006', 1, 2, 5);

-- 3. Insert N/A fallbacks for other subsidiaries
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_002', 2, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_003', 3, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_004', 4, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_005', 5, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_006', 6, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_007', 7, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_008', 8, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_009', 9, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_010', 10, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_011', 11, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_012', 12, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_013', 13, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_014', 14, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_015', 15, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_016', 16, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_017', 17, 2, 99);
INSERT INTO organizations (name, code, parent_id, depth, sort_order) VALUES ('해당없음', 'NA_018', 18, 2, 99);
