name = "sguardai"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
ENVIRONMENT = "production"
DIFY_API_KEY = "app-owwPp3j2qAvVDZpW2UUiY8L3"
DIFY_API_KEY_DASHBOARD = "app-TSlqmp329iKOzpXUP90iC6Kw"
DIFY_API_KEY_ASSISTANT = "app-ZDaVB8EWtA5vmTYJLmbysdQq"
DIFY_API_KEY_SUMMARIZER = "app-owwPp3j2qAvVDZpW2UUiY8L3"
DIFY_API_KEY_GOVERNANCE = "app-QHxJQTBSKJlTw2gVeGgTk915"
DIFY_API_BASE = "https://api.dify.ai/v1"
DIFY_TOOL_KEY = "!QweAsd1018"

[ai]
binding = "AI"

[durable_objects]
bindings = [
  { name = "WARROOM_DO", class_name = "WarRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WarRoom"]

[[kv_namespaces]]
binding = "SMS_STORAGE"
id = "2b426805a38f4403ac1e4f8a03c22d00"

[[r2_buckets]]
binding = "WARROOM_ASSETS"
bucket_name = "sguard-warroom-assets"

[[vectorize]]
binding = "WARROOM_INDEX"
index_name = "sguard-warroom-index"

[[d1_databases]]
binding = "DB"
database_name = "sguard-db"
database_id = "cec6c7cc-5bce-4fdf-a500-e1976b1fb66f"
